### ISSUE TITLE
custom scripts folder

### ISSUE THREAD

**Issue by sigmafrlol** [SyndiShanX/Synergy-IW-GSC-Menu#1]
i cant find it

**Comment by SyndiShanX** [comment]
Can’t find what?

**Comment by SyndiShanX** [comment]
You have to make the folders yourself

**Comment by sigmafrlol** [comment]
> You have to make the folders yourself

okay what should the name of the folder be?

**Comment by SyndiShanX** [comment]
Inside of the `iw7-mod` folder you make a `custom_scripts` folder, then a `cp` folder inside of that

**Comment by sigmafrlol** [comment]
k ty
