### ISSUE TITLE
Special weapons on other maps execpt spaceland not working

### ISSUE THREAD

**Issue by fedd97** [SyndiShanX/Synergy-IW-GSC-Menu#2]
hi, first thing first awesome mod menu, great work! Sadly the special weapons you get on other maps from the menu are not working

**Comment by SyndiShanX** [comment]
Which weapons and what happens when you try to get them?

**Comment by SyndiShanX** [comment]
Ok, I found an issue with the Rave Weapons and will be Pushing a fix soon

**Comment by SyndiShanX** [comment]
Thanks for Reporting, Comment again if you still have issues

**Comment by fedd97** [comment]
thank you for the quick fix, will definitely check!
